"""Canonical NAV store + export into the Next.js data layer.

Canonical source of truth: pipeline/data/nav-history.json
    { "SIF-3": { "2026-08-03": 11.0198, ... }, ... }
Keyed by (code, ISO-date) so re-runs upsert idempotently and git diffs stay clean.

Exports into lib/data/raw/ — NOT into public/. DESIGN_CONTRACT §1.13 requires
every number on the site to trace to `@/lib/data`, so the app imports this JSON
rather than fetching it at runtime.

    lib/data/raw/nav-history.json   { asOf, source, series: { "SIF-3": [[date, nav], ...] } }
    lib/data/raw/schemes.json       patched in place: each scheme's `nav` + `navAsOf`

Series are [date, nav] pairs rather than objects: same information, ~40% fewer
bytes in the route bundle.
"""
from __future__ import annotations

import json
import os

_PIPELINE_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_DIR = os.path.abspath(os.path.join(_PIPELINE_DIR, ".."))

HISTORY_PATH = os.path.join(_PIPELINE_DIR, "data", "nav-history.json")
RAW_DIR = os.path.join(_PROJECT_DIR, "lib", "data", "raw")
APP_HISTORY_PATH = os.path.join(RAW_DIR, "nav-history.json")
SCHEMES_PATH = os.path.join(RAW_DIR, "schemes.json")

# Kept so log lines that print an output directory still resolve.
PUBLIC_NAV_DIR = RAW_DIR

History = dict[str, dict[str, float]]


def _code_sort_key(code: str) -> tuple[int, int | str]:
    try:
        return (0, int(code.split("-")[1]))
    except (IndexError, ValueError):
        return (1, code)


def load_history() -> History:
    if not os.path.exists(HISTORY_PATH):
        return {}
    with open(HISTORY_PATH, encoding="utf-8") as f:
        return json.load(f)


def save_history(history: History) -> None:
    os.makedirs(os.path.dirname(HISTORY_PATH), exist_ok=True)
    ordered = {
        code: {d: history[code][d] for d in sorted(history[code])}
        for code in sorted(history, key=_code_sort_key)
    }
    with open(HISTORY_PATH, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)
        f.write("\n")


def upsert(history: History, code: str, iso_date: str, nav: float) -> bool:
    """Insert/update one (code, date) -> nav. True if it added or changed."""
    series = history.setdefault(code, {})
    if series.get(iso_date) == nav:
        return False
    series[iso_date] = nav
    return True


def export_frontend(history: History, names: dict[str, str]) -> None:
    """Write lib/data/raw/nav-history.json and patch schemes.json in place."""
    os.makedirs(RAW_DIR, exist_ok=True)

    series = {
        code: [[d, history[code][d]] for d in sorted(history[code])]
        for code in sorted(history, key=_code_sort_key)
        if history[code]
    }
    as_of = max((s[-1][0] for s in series.values()), default=None)

    with open(APP_HISTORY_PATH, "w", encoding="utf-8") as f:
        json.dump(
            {
                "source": "AMFI — https://portal.amfiindia.com/spages/SIF_NAVAll.txt",
                "asOf": as_of,
                "_comment": "GENERATED by pipeline/. Series are [ISO date, NAV] pairs "
                            "per AMFI scheme code, ascending. Do not hand-edit.",
                "series": series,
            },
            f,
            ensure_ascii=False,
            separators=(",", ":"),
        )
        f.write("\n")

    points = sum(len(v) for v in series.values())
    print(f"  nav-history.json: {len(series)} schemes, {points} observations, "
          f"as at {as_of}")
    _patch_schemes(series, as_of)


def _patch_schemes(series: dict[str, list], as_of: str | None) -> None:
    """Bring each scheme's latest NAV in schemes.json up to date with the feed.

    Only `nav` / `navAsOf` are touched. Identity, disclosures and the AMC
    mapping in that file are researched by hand and authoritative — the
    pipeline must never overwrite them.
    """
    if not os.path.exists(SCHEMES_PATH) or as_of is None:
        return
    with open(SCHEMES_PATH, encoding="utf-8") as f:
        doc = json.load(f)

    changed = 0
    missing = []
    for scheme in doc.get("schemes", []):
        code = scheme.get("amfiSchemeCode")
        points = series.get(code)
        if not points:
            missing.append(code)
            continue
        last_date, last_nav = points[-1]
        if scheme.get("nav") != last_nav or scheme.get("navAsOf") != last_date:
            scheme["nav"] = last_nav
            scheme["navAsOf"] = last_date
            changed += 1

    doc["navAsOf"] = as_of
    with open(SCHEMES_PATH, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"  schemes.json: refreshed {changed} scheme NAV(s), navAsOf -> {as_of}")
    if missing:
        print(f"  WARNING: no series for {missing} — left untouched")
